import {createServer} from '../node_modules/vite/dist/node/index.js';
import fs from 'node:fs';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url)).replace(/\/$/,''),server=await createServer({root,server:{middlewareMode:true}}),g=await server.ssrLoadModule('/src/world-geometry.ts'),r=await server.ssrLoadModule('/src/refinement.ts');
const read=p=>JSON.parse(fs.readFileSync(root+'/public/'+p)),data=read('overall/data.json'),plans=read('refined-plans.json'),geo=g.geometry(data,read('campus.json')),reg=r.refine(geo,data,plans),origin=g.toWorld(data.places.find(p=>p.id==='dorm56').point),shift=reg.find(r=>r.id==='dorm56').translation,o=origin.map((v,i)=>v+shift[i]);
const all=geo.buildings.map(b=>({fp:b.footprint,box:[Math.min(...b.footprint.map(p=>p[0]))-2,Math.max(...b.footprint.map(p=>p[0]))+2,Math.min(...b.footprint.map(p=>p[1]))-2,Math.max(...b.footprint.map(p=>p[1]))+2]}));
const safe=p=>g.inside(p,geo.land)&&!all.some(b=>p[0]>b.box[0]&&p[0]<b.box[1]&&p[1]>b.box[2]&&p[1]<b.box[3]&&(g.inside(p,b.fp)||b.fp.some((q,i)=>g.distance(p,g.closest(p,q,b.fp[(i+1)%b.fp.length]))<1.9)));
const line=(a,b)=>{const n=Math.ceil(g.distance(a,b)/.65);for(let i=0;i<=n;i++)if(!safe(a.map((v,k)=>v+(b[k]-v)*i/(n||1))))return false;return true;};
const key=p=>p.join(','),pt=k=>k.split(',').map(Number),cache=new Map(),valid=k=>{if(!cache.has(k))cache.set(k,safe(pt(k)));return cache.get(k);};
function snap(p){let best;for(let d=0;d<=14;d+=2){const a=[Math.round(p[0]/2)*2,Math.round(p[1]/2)*2];for(let x=-d;x<=d;x+=2)for(let z=-d;z<=d;z+=2){const q=[a[0]+x,a[1]+z];if(valid(key(q))&&(!best||g.distance(p,q)<g.distance(p,best)))best=q;}if(best)return best;}throw Error('no safe anchor '+p);}
class Heap{a=[];push(v){let i=this.a.push(v)-1;while(i){let p=(i-1)>>1;if(this.a[p].f<=v.f)break;this.a[i]=this.a[p];i=p;}this.a[i]=v;}pop(){const first=this.a[0],last=this.a.pop();if(this.a.length){let i=0;while(i*2+1<this.a.length){let c=i*2+1;if(c+1<this.a.length&&this.a[c+1].f<this.a[c].f)c++;if(last.f<=this.a[c].f)break;this.a[i]=this.a[c];i=c;}this.a[i]=last;}return first;}}
function route(a,b){if(line(a,b))return[a,b];const start=key(a),goal=key(b),open=new Heap(),cost=new Map([[start,0]]),prev=new Map();open.push({k:start,f:g.distance(a,b),c:0});let runs=0;while(open.a.length){const cur=open.pop();if(cur.c!==cost.get(cur.k))continue;if(cur.k===goal){let out=[b],k=goal;while(k!==start){k=prev.get(k);out.push(pt(k));}out.reverse();const short=[out[0]];for(let i=0;i<out.length-1;){let j=out.length-1;while(j>i+1&&!line(out[i],out[j]))j--;short.push(out[j]);i=j;}return short;}if(++runs>90000)throw Error('route budget '+a+' '+b);const p=pt(cur.k);for(const dx of [-2,0,2])for(const dz of [-2,0,2]){if(!dx&&!dz)continue;const q=[p[0]+dx,p[1]+dz],k=key(q),c=cur.c+Math.hypot(dx,dz);if(Math.abs(q[0]-o[0])>270||Math.abs(q[1]-o[1])>270||!valid(k)||!line(p,q)||c>=(cost.get(k)??Infinity))continue;cost.set(k,c);prev.set(k,cur.k);open.push({k,c,f:c+g.distance(q,b)});}}throw Error('no path '+a+' '+b);}
// Reject safe but isolated grid pockets in narrow gaps before choosing waypoint anchors.
const reachable=new Set(),seed=snap(plans.dorm56.walkways[0].points[0].map((v,i)=>v+o[i])),queue=[seed];reachable.add(key(seed));
for(let qi=0;qi<queue.length;qi++){const p=queue[qi];for(const dx of [-2,0,2])for(const dz of [-2,0,2]){if(!dx&&!dz)continue;const q=[p[0]+dx,p[1]+dz],k=key(q);if(reachable.has(k)||Math.abs(q[0]-o[0])>270||Math.abs(q[1]-o[1])>270||!valid(k)||!line(p,q))continue;reachable.add(k);queue.push(q);}}
const reachableSnap=p=>{let best;for(let d=0;d<=20;d+=2){const a=[Math.round(p[0]/2)*2,Math.round(p[1]/2)*2];for(let x=-d;x<=d;x+=2)for(let z=-d;z<=d;z+=2){const q=[a[0]+x,a[1]+z];if(reachable.has(key(q))&&(!best||g.distance(p,q)<g.distance(p,best)))best=q;}if(best)return best;}throw Error('no reachable anchor '+p);};
console.log('reachable nodes',reachable.size);
const output=[],network=[];for(const input of plans.dorm56.walkways){let anchors=input.points.map(p=>reachableSnap(p.map((v,i)=>v+o[i])));
 if(input.name.includes('入口')){let end=anchors.length-1;const nr=geo.nearestRoad(anchors[end]);anchors.push(reachableSnap(nr.point));}
 let points=[anchors[0]];for(let i=1;i<anchors.length;i++)points.push(...route(anchors[i-1],anchors[i]).slice(1));
 if(network.length){let link;for(const end of [0,points.length-1])for(const n of network){const d=g.distance(points[end],n);if(!link||d<link.d)link={end,n,d};}if(link.d>.1){const connector=route(points[link.end],link.n);if(link.end===0)points=[...connector.reverse().slice(0,-1),...points];else points.push(...connector.slice(1));}}
 points=points.filter((p,i)=>!i||g.distance(p,points[i-1])>.01);network.push(...points);output.push({...input,points:points.map(p=>p.map((v,i)=>v-o[i]))});
}
plans.dorm56.walkways=output;fs.writeFileSync(root+'/public/refined-plans.json',JSON.stringify(plans,null,2)+'\n');console.log({paths:output.length,vertices:network.length,length:output.reduce((s,p)=>s+p.points.slice(1).reduce((a,b,i)=>a+g.distance(p.points[i],b),0),0)});await server.close();
